# permissions for end users to view appcharts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appchart-viewer-role
rules:
- apiGroups:
  - application.epinio.io
  resources:
  - appcharts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.epinio.io
  resources:
  - appcharts/status
  verbs:
  - get
