# permissions for end users to edit servicereleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicerelease-editor-role
rules:
- apiGroups:
  - application.epinio.io
  resources:
  - servicereleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.epinio.io
  resources:
  - servicereleases/status
  verbs:
  - get
