# permissions for end users to view services.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-viewer-role
rules:
- apiGroups:
  - application.epinio.io
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.epinio.io
  resources:
  - services/status
  verbs:
  - get
