apiVersion: application.epinio.io/v1
kind: Service
metadata:
  name: service-sample
  namespace: epinio
spec:
  name: service-sample
  shortDescription: |
    A simple description of this service.
  description: |
    A longer description of the same service. This will be used when describing
    this service.
  chart: postgresql
  helmRepo:
    name: bitnami
    url: "https://charts.bitnami.com/bitnami"
  values: |
    auth:
      enablePostgresUser: true
      postgresPassword: foobar
